package it.polimi.ingsw.server.enumerations;

public enum MessageType {
    PING,
    ERROR,
    LOGIN_REQUEST,
    LOGIN_REPLY,
    PLAYER_NUMBER_REQUEST,
    PLAYER_NUMBER_REPLY,
    GENERIC_MESSAGE,
    MOVE_MOTHER_NATURE,
    WINNER_DECLARATION,
    LOBBY,
    DISCONNECTED_PLAYER,
    MOVE_STUDENT,
    PICK_CLOUD,
    MERGE_ISLANDS,
    PLAY_ASSISTANT_CARD,
    GAME_MODE,
    USE_EFFECT;
}
